CREATE TABLE IF NOT EXISTS `ao_credit_pipeline_targets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periode_bulan` CHAR(7) NOT NULL,
  `closing_date` DATE DEFAULT NULL,
  `harian_date` DATE DEFAULT NULL,
  `no_rekening` VARCHAR(30) NOT NULL,
  `kode_kantor` VARCHAR(3) NOT NULL,
  `kode_ao` VARCHAR(30) DEFAULT NULL,
  `ao_employee_id` VARCHAR(30) DEFAULT NULL,
  `target_pokok_awal_bulan` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `target_bunga_awal_bulan` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `catatan` VARCHAR(255) DEFAULT NULL,
  `input_by` VARCHAR(30) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_periode_rekening` (`periode_bulan`, `no_rekening`),
  KEY `idx_ao_credit_pipeline_targets_ao` (`ao_employee_id`),
  KEY `idx_ao_credit_pipeline_targets_cabang` (`kode_kantor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `ao_credit_portfolio_activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `no_rekening` VARCHAR(30) NOT NULL,
  `kode_kantor` VARCHAR(3) NOT NULL,
  `kode_ao` VARCHAR(30) DEFAULT NULL,
  `ao_employee_id` VARCHAR(30) DEFAULT NULL,
  `jenis_tindakan` VARCHAR(20) NOT NULL,
  `kode_tindakan` VARCHAR(20) DEFAULT NULL,
  `lokasi_tindakan` VARCHAR(50) DEFAULT NULL,
  `orang_ditemui` VARCHAR(50) DEFAULT NULL,
  `nominal_janji` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `tanggal_janji` DATE DEFAULT NULL,
  `keterangan` TEXT DEFAULT NULL,
  `latitude` DECIMAL(12,8) DEFAULT NULL,
  `longitude` DECIMAL(12,8) DEFAULT NULL,
  `geo_address` VARCHAR(255) DEFAULT NULL,
  `foto_path` VARCHAR(255) DEFAULT NULL,
  `created_by` VARCHAR(30) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ao_credit_portfolio_activities_rekening` (`no_rekening`),
  KEY `idx_ao_credit_portfolio_activities_ao` (`ao_employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
